# Generated by Django 3.1.1 on 2020-09-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='productPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('productname', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('productstate', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(help_text='(00237)(number)', max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='product.category')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimages')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='product.subcategory')),
            ],
        ),
    ]
