# Generated by Django 3.1.1 on 2020-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200906_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='dealoftheday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpost',
            name='hotdeal',
            field=models.BooleanField(default=False),
        ),
    ]
