# Generated by Django 3.1.1 on 2020-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200907_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpost',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpost',
            name='storage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
