# Generated by Django 3.1.1 on 2020-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200915_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpost',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
