# Generated by Django 3.1.1 on 2020-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dealname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
