# Generated by Django 3.1.1 on 2020-09-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200921_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deal',
            new_name='ProductDeal',
        ),
    ]
