# Generated by Django 3.1.1 on 2020-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200921_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdeal',
            name='dealname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
