# Generated by Django 3.1.1 on 2020-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200921_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cat',
        ),
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.ManyToManyField(null=True, related_name='subcat', to='product.subCategory'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='contact',
            field=models.CharField(help_text='(237)(number)', max_length=100, null=True),
        ),
    ]
