# Generated by Django 3.1.1 on 2020-09-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200922_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdeal',
            name='dealimg',
            field=models.ImageField(help_text='picture of the gift', null=True, upload_to='dealimg'),
        ),
        migrations.AlterField(
            model_name='productdeal',
            name='dealname',
            field=models.CharField(help_text='deal name example free winex as gift', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productdeal',
            name='description',
            field=models.TextField(blank=True, help_text='description of the gift', null=True),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='product.category'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='select product category', null=True),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='dealoftheday',
            field=models.BooleanField(default=False, help_text='click if there is a gift out for this product'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='hotdeal',
            field=models.BooleanField(default=False, help_text='click if there is a gift out for this product'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='subcat',
            field=models.ForeignKey(help_text='select product sub category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='product.subcategory'),
        ),
    ]
