# Generated by Django 3.1.1 on 2020-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200927_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='sellername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
