# Generated by Django 3.1.1 on 2020-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bothSellerAndBuyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customercare',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preadminone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
